-- Create the ingredient_mappings table
create table ingredient_mappings (
  id bigint generated by default as identity primary key,
  rule_value text not null unique,
  synonyms text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add some initial data
insert into ingredient_mappings (rule_value, synonyms)
values 
  ('palm oil', array['palm kernel oil', 'palmitate', 'vegetable oil (palm)', 'palm stearin', 'sodium lauryl palmitate', 'palm olein']),
  ('peanuts', array['peanut', 'groundnut', 'arachide', 'arachis hypogaea', 'monkey nuts']),
  ('soy', array['soybeans', 'soya', 'textured vegetable protein', 'tvp', 'edamame', 'tofu', 'tempeh', 'miso', 'soy lecithin']),
  ('milk', array['dairy', 'whey', 'casein', 'lactose', 'cream', 'butter', 'ghee', 'buttermilk', 'cheese']),
  ('wheat', array['wheat flour', 'semolina', 'durum', 'spelt', 'kamut', 'seitan', 'bulgur', 'couscous', 'gluten']);

-- Create an index on rule_value for faster lookups
create index idx_ingredient_mappings_rule_value on ingredient_mappings(rule_value);

-- Add trigger for updated_at
create or replace function trigger_set_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_ingredient_mappings_timestamp
  before update on ingredient_mappings
  for each row
  execute function trigger_set_timestamp();